theme: jekyll-theme-minimal

title: Magtheridon EU

description: An open source community website for the players on Magtheridon (EU).

google_analytics: UA-81429436-1

gems:
  - jekyll-sitemap

collections:
- guilds

defaults:
  -
    scope:
      path: "/_posts/" # an empty string here means all files in the project
    values:
      layout: "blogpost"
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
